   CREATE TABLE PET 
   (	ID INTEGER, 
	AGE INTEGER, 
	HISTORY VARCHAR(500), 
	NAME VARCHAR(20) NOT NULL, 
	SEX BOOLEAN, 
	"TYPE" VARCHAR(20)
   );
   
   CREATE TABLE CAT 
   (	ID INTEGER, 
	BREED VARCHAR(20) NOT NULL, 
	"CHARACTER" VARCHAR(20), 
	WOOL_LENGTH VARCHAR(20) NOT NULL
   );
   
     CREATE TABLE DOG
   (	"ID" INTEGER NOT NULL, 
	"BREED" VARCHAR(20) NOT NULL, 
	"CHARACTER" VARCHAR(20)
   ) 
  
  CREATE TABLE BIRD 
   (	"ID" INTEGER NOT NULL, 
	"BREED" VARCHAR(20) NOT NULL, 
	"IS_SINGING" BOOLEAN NOT NULL
   ) 